### ISSUE TITLE
Impossible d’utiliser Lovelace pronote 

### ISSUE THREAD

**Issue by CyrilleDevolder** [delphiki/lovelace-pronote#15]
Bonjour,
Comme vous pouvez le voir sur la photo, après avoir installé Lovelace pronote et rechargé l’IHM, il est impossible d’utiliser Lovelace pronote car il ne trouve pas l’ensemble des types.
Y’a-t’il une manipulation à faire ?

merci bcp.

![IMG_9085](https://github.com/delphiki/lovelace-pronote/assets/100042296/941530f9-f223-403f-a2e7-148d8ced3de2)

**Comment by vvince62550** [comment]
Hello,
J'ai exactement le même problème.
J'ai également essayé une version plus ancienne.

Merci

**Comment by delphiki** [comment]
Hello,

Avez-vous essayé de vider le cache de votre navigateur ?

**Comment by vvince62550** [comment]
> Hello,
> 
> Avez-vous essayé de vider le cache de votre navigateur ?

Oui bien sûr.
J'ai également fait d'autres intégration (lovelace meteo France par exemple) et je n'ai pas eu de soucis.

Merci

**Comment by CyrilleDevolder** [comment]
Idem, j’ai aussi vider le cache, j’ai le problème sur PC et iPhone.

**Comment by vvince62550** [comment]
Hello,
J'ai mon PC pour lequel toutes les cartes sont KO.

Par contre sur l'application 3 sont apparues du jour au lendemain sans manipulations :
- Notes 
- Emploi du temps
- Devoirs
Les 3 autres (absences, moyennes et évaluations sont toujours KO).

Auriez vous une idée ? Merci

**Comment by Mikeke48** [comment]
Bonjour,
J'avais le même soucis à l'installation ce jour, j'ai importé manuellement le dossier cards sous HACS et depuis ça marche parfaitement.
A+
<img width="768" alt="hacs pronote" src="https://github.com/delphiki/lovelace-pronote/assets/166937247/2132b36b-c0a9-4a75-b012-9af4455cb19c">

**Comment by Mikeke48** [comment]
Bonjour,
J'avais le même soucis à l'installation ce jour, j'ai importé manuellement le dossier cards sous HACS et depuis ça marche parfaitement (cf_ci-dessous)
Je pense que la copie des cartes ne se fait pas lors de l'installation du repo.

A+ 
edit (anonymisation du nom des profs)
<img width="768" alt="hacs pronote" src="https://github.com/delphiki/lovelace-pronote/assets/166937247/b8b6ed07-c8d5-49eb-98f4-caf2c950b634">

**Comment by delphiki** [comment]
@sinseman44 Hello,

est-ce que tu peux me dire si les attributs que tu as pour le sensor que tu utilises avec la carte (timetable j'imagine) sont bien présents ?

**Comment by sinseman44** [comment]
> @sinseman44 Hello,
> 
> est-ce que tu peux me dire si les attributs que tu as pour le sensor que tu utilises avec la carte (timetable j'imagine) sont bien présents ?

Salut,

Pour répondre à ta question, j'ai pris la carte "emploi du temps" en utilisant l'exemple du README (en remplaçant le XXXX par le nom de famille et YYYY par le prénom) par l'entité configurée sur mon HA :
```
type: custom:pronote-timetable-card
entity: sensor.pronote_XXXX_YYYY_timetable_next_day
display_header: true
display_lunch_break: true
display_classroom: true
display_teacher: true
display_day_hours: true
dim_ended_lessons: true
max_days: null
current_week_only: false
```
et ca fonctionne bien ! Effectivement l'entité `sensor.pronote_XXXX_YYYY_timetable_next_day` est bien renseigné dans mon HA !

Si maintenant je teste la carte suivante (homework), l'entité n'est pas remplie dans mon HA : 
```
type: custom:pronote-homework-card
entity: sensor.pronote_XXXX_YYYY_homework
display_header: true
display_done_homework: true
reduce_done_homework: true
current_week_only: false
```

![pronote_err_1](https://github.com/user-attachments/assets/a1513e85-63b2-4004-8ad5-a3e8df8e801b)

et la carte homework n'affiche rien effectivement avec l'erreur suivante (dans l'inspecteur de la page web) : 

```
pronote.js?hacstag=740139503161:121 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'date')
    at C.render (pronote.js?hacstag=740139503161:121:202)
    at C.update (lit-element.ts:160:24)
    at C.performUpdate (reactive-element.ts:1329:14)
    at C.scheduleUpdate (reactive-element.ts:1261:17)
    at C._$Ej (reactive-element.ts:1233:25)
```

Ma première erreur a été de copier/coller les exemples donnés dans le README sans me rendre compte qu'il fallait remplacer XXXX et YYYY => Il faudrait peut-être le mentionner dans le README pour les étourdis (comme moi :) ).

Comme c'est le début d'année scolaire, je pense que l'API `pronote` ne remonte pas encore les informations de toutes les entités définies par l'intégration de mon HA. c'est pourquoi certaines cartes ne fonctionne pas. => Serait-il possible d'afficher la carte avec une mention comme "Aucune donnée disponible" ou quelque chose comme ca au lieu de rien ?

**Comment by sinseman44** [comment]
Update de mon dernier post, avec la dernière version 1.6.2, la carte pronote-homework affiche bien une information "Pas de devoirs" 👍

**Comment by Titou84240** [comment]
Bonjour à tous , si ça peut aider aussi , pour ceux qui n'utilise pas Lovelace en mode stockage pensez a faire ceci : 

![image](https://github.com/user-attachments/assets/8965e828-2c33-4bea-b9da-edbbb97a0494)

**Comment by OlivierHA69** [comment]
Bonjour,

J'ai suivi toute la procédure mais je ne vois pas les cartes Pronote quand j'essaye de les ajouter dans un design. :-(
SI quelqu'un a une idée je suis preneur. 
Merci par avance

<img width="1559" alt="image" src="https://github.com/user-attachments/assets/c160a1aa-19f8-4fd9-be66-98b75025aa57">

**Comment by delphiki** [comment]
Hello @OlivierHA69, 

Pour le moment elles ne sont pas listées dans l'interface de choix des cartes.
Il faut que tu fasses un ajout manuel et que tu utilises le YAML.

Normalement l'ajout dans le listing et les éditeurs visuels seront dispo dans la future màj.
